### ISSUE TITLE
Neo4TSTypes.GraphAbstraction returns 'hasOwnProperty' error

### ISSUE THREAD

**Issue by AntonioCahuich** [kingskull619/Neo4Ts#5]
Getting 'hasOwnProperty' when using Neo4TSTypes.GraphAbstraction and query matches results with that pattern

TypeError: Cannot read property 'hasOwnProperty' of null
    at isNode (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:1339:22)
    at mapGraphEntities (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:1329:7)
    at mapEntities (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:1322:33)
    at mapToDto (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:1307:19)
    at RetrieveBuilder._callee$ (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:1512:48)
    at tryCatch (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:163:40)
    at Generator.invoke [as _invoke] (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:394:22)
    at Generator.next (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:219:21)
    at asyncGeneratorStep (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:9:24)
    at _next (C:\Projects\pt4-ms-reportanddashboard\node_modules\neo4ts\dist\neo4ts.cjs.development.js:31:9)

**Comment by CarlosHPlata** [comment]
Fixed on version 0.1.3
